/*
 * //!>
 * 
 * @startuml uk/ac/warwick/wsbc/QuimP/doc-files/stats_1.png
 * Bob -> Alice : hello
 * Alice --> Bob : OK
 * @enduml
 * 
 * //!<
 */
/**
 * This is the main package.
 * 
 * Below there are fragments of QuimP architecture.
 * 
 * <h1>Architecture</h1>
 * <h2>Generating statistic files</h2>
 * 
 * Statistics generated by QuimP are related to cell shape and fluorescence distribution along cell
 * cortex. They are stored in <i>stQP.csv</i> and <i>QCONF</i> files but they are build on different
 * stages of processing.
 * 
 * <h1>Code rules</h1>
 */
package uk.ac.warwick.wsbc.QuimP;