selectWindow("2014879.png");
run("Split Channels");
imageCalculator("Subtract create", "2014879.png (blue)","2014879.png (red)");
selectWindow("Result of 2014879.png (blue)");
run("Gaussian Blur...", "sigma=10");
setAutoThreshold("Default dark");
//run("Threshold...");
setAutoThreshold("Default");
setThreshold(27, 255);
run("Convert to Mask");
run("Analyze Particles...", "size=3000-Infinity circularity=0.50-1.00 show=Nothing display exclude clear summarize add");